---
title: "Evaluation of the Effect of Donor Hyperglycemia on Recipient Peri-Transplant Liver Function"
format: pdf
author: "Rishvitha, Brandon, Ahana, Samprokshana"
editor: visual
embed-resources: true
echo: false 
---

```{r}
library(tidyverse)
theme_set(theme_minimal())
echo = FALSE
```

**Introduction**

Liver disease and failure is one of the most prevalent conditions affecting populations globally, accounting for around 2 million annual deaths worldwide ([Devarbhavi et al., 2023)](https://www.zotero.org/google-docs/?PhumxJ). Furthermore, cirrhosis, or the final stage of chronic liver failure, is the fourth leading cause of premature death in the US, eliciting the need for effective treatments ([Khalil et al., 2023; Liu & Chen, 2022)](https://www.zotero.org/google-docs/?ykTcL0). Although invasive and non-invasive methods of treatment can address liver failure to a certain extent, systematically improving these techniques can greatly improve patient outcomes. Since liver transplants remain the common method of treating liver disease, determining the relationship between post-operative liver function in transplant recipients and external factors can significantly reduce the burden of liver disease ([Khalil et al., 2023](https://www.zotero.org/google-docs/?Wsl6Ef)). 

Current research has identified that critical environmental circumstances, such as the organ-donor shortage, have necessitated high-risk organ donors, which can lead to successful liver transplants with short-lived function (Khalil et al., 2023). Furthermore, studies have identified characteristics of the patient, such as BMI and age, that can negatively influence liver function outcomes ([Pischke et al., 2017)](https://www.zotero.org/google-docs/?Hwm9m2). However, there is a lack of research regarding donor risk factors that can complicate liver function after successful transplants, which must be identified to ensure long-term treatment efficacy. Since intraoperative and peri-transplant hyperglycemia can lead to severe consequences (such as graft rejection and patient mortality), hyperglycemia should be considered a crucial factor in choosing organ donors [(Rameshi et al., 2025)](https://www.zotero.org/google-docs/?4i1SZk). 

Although many donor characteristics could create high-risk transplant circumstances, this paper conducts statistical analyses specifically on the association between donor hyperglycemia and recipient liver function, as it has been least explored. Since statistical modeling can provide sufficient or insufficient evidence of an association between donor hyperglycemia and liver function in the patient, the analyses in this paper are critical for developing a rich understanding behind one of the most prominent medical diseases globally. The insights from this analysis will directly inform the diagnosis of peri-operative liver function, help medical professionals create stricter guidelines for donors, and facilitate successful liver transplant outcomes overall.

**Figure 1**

By building upon the factors regarding liver failure from Figure 1 adapted from [Rameshi et al., (2025)](https://www.zotero.org/google-docs/?eRjL7S), this analysis reveals how specific donor related factors, such as hyperglycemia, can affect peri-liver transplant function. While recipient factors and intraoperative factors have been greatly studied (as seen by the visual complexity of those two domains), this visualization outlines the lack of research on donor factors – a gap in research that this paper aims to close. 

**Data**

The data utilized in the statistical analysis is obtained from [Perez-Protto et al. (2014)](https://www.zotero.org/google-docs/?f2a5U4), which studied the relationship between donor hyperglycemia and liver function outcome to create glucose-management systems in donors. For the dataset, information on 591 liver transplants in the Cleveland Clinic was collected during a five-year period. Data regarding grafts, donors, and recipients was obtained while “grafts from living donors, donors after cardiac death, and transplants for which the donor’s glucose level was measured fewer than 2 times” were excluded [(Perez-Protto et al., 2014)](https://www.zotero.org/google-docs/?4EqW5y). While the dataset includes important information regarding the demographics and characteristics of both donors and patients, this analysis will primarily focus on the relationship between two variables: time-weighted average (TWA) of of glucose observations in the liver graft and delayed liver function. Additionally, to produce more accurate results, donor age, donor gender, recipient calculated model for end-stage liver disease (MELD) score, and donor intraoperative hemodynamic instability will be accounted for. Recipient calculated MELD score represents how severe the state of a recipient’s liver disease is, with scores ranging from 6-40 and higher scores indicating a more severe condition. Intraoperative hemodynamic instability indicates that a donor had abnormal blood flow to organs during surgical operations.

**Operationalization of Variables**

For the purpose of this statistical analysis, the variable of TWA glucose observations in the liver graft above 200 mg/dL is considered as donor hyperglycemia as per the foundational paper and other literature ([Oliveira et al., 2018; Perez-Protto et al., 2014)](https://www.zotero.org/google-docs/?Pb4STo). Delayed graft dysfunction, or the patient’s liver outcome, is categorized as either dysfunction by patient death or retransplant within one week peri-transplant, or by having “aspartate aminotransferase level greater than 2000 U/L or prothrombin time greater than 16 seconds any time between postoperative days 2 and 7” [(Perez-Protto et al., 2014, p.107)](https://www.zotero.org/google-docs/?uZRLB1). If either of these conditions were met, liver function was described as dysfunctional, and if either were not, liver function was described as functional. For this statistical analysis, TWA glucose levels, donor age, donor gender, recipient calculated model for end-stage liver disease (MELD) score, and donor intraoperative hemodynamic instability will serve as the explanatory variables, while delayed liver function is the response variable. Although the foundational paper aimed to analyze the relationship between the same two variables, the analysis in this paper can be used to confirm or deny the findings of Perez-Proto et al. (2014). By analyzing the association between TWA glucose levels and delayed liver function specifically, the statistical analysis conducted will provide the basis for future research on donor factors regarding recipient hepatic outcomes.

**Methodology**

Our question investigates whether donor hyperglycemia (TWA glucose \> 200 mg/dL) is associated with delayed liver function, represented through a binary outcome of either functional (Y = 0) or dysfunctional (Y=1). Since delayed graft functionality is binary, logistic regression must be used rather than linear regression which assumes a continuous outcome, and can predict values outside 0-1. Logistic regression allows us to estimate the probability of dysfunction based upon predictors, with p = P ( Y=1 \| predictors). This is modeled using log odds, expressed as a linear function of predictors and coefficients. Log-odds are then transformed back into p, for the probability of delayed liver function beind dysfunctional, p = e\^log odds / (1-e\^log odds). 

Additionally, logistic regression allows for adjustment of multiple factors including donor age, donor sex, recipient MELD score, and intraoperative hemodynamic stability. Categorical variables are coded with reference codes and continuous variables to their median values. As a result, we receive an independent estimate of how donor hyperglycemia affects graft dysfunction. Using the odds ratio, we can learn how odds of dysfunction increase with a unit change in glucose while keeping other factors constant.

\

Logistic regression assumes that observations are independent, which is satisfied as each row of our dataset represents a unique donor to recipient transplant. 

\

The outcome variable is delayed graft dysfunction,  determined through either primary nonfunction (death of retransplant in the first preoperative week) or through biochemical dysfunction (AST greater than 2000 U/L or prothrombin time greater than 16 second during postoperative days 2-7). Delayed graft dysfunction is represented as a binary variable, coded as 

0 = functional graft and 1 = dysfunctional graft. Therefore, the model estimates p = P(Y=1 \| predictors). Donor Hyperglycemia is our main exploratory variable, represented as time weighted average glucose level \> 200 mg/dL. Other exploratory variables include donor age (continuous), donor gender (categorial, reference = male), recipient MELD score (continuous), and donor intraoperative hemodynamic instability (binary). Our model applies the following equation:

log(p/1-p​)=β0​+β1​(Hyperglycemia)+β2​(Donor Age)+β3​(Donor Gender (Female))+β4​(MELD)+β5​(Hemodynamic Instability)

Using R studio, we apply the generalized linear model, setting family = binomial to use logistic regression, and inputting our variable names. Our study aims to determine the association between donor TWA glucose and odds of delayed graft function. 

**Discussion**

To summarize our findings, the modeled coefficients indicate a slight positive association between donor TWA glucose and odds of delayed graft function, at around 1.29 times higher odds per 100 mg/dL increase in donor TWA glucose. Donor age, donor sex, and recipient MELD also have positive but small effects on the odds of delayed graft function, while the donor intraoperative hemodynamic instability coefficient is slightly negative. These findings contribute to addressing the gap in research centered around the donor and suggest that improved glucose management in donors could strengthen peri-transplant outcomes for the recipient.

The goal of our research was met, as we intended to assess the relationship between donor hyperglycemia and liver function in the patient. The results supported our initial hypothesis as higher donor TWA glucose is associated with increased log-odds of delayed graft function, indicating that donor hyperglycemia does in fact cause detrimental liver effects for the recipient. This data was obtained while all other variables were held constant, however we also observed changes in the delayed liver graft function when manipulating other factors of the donor and recipient. For example, an increase in donor age, donor’s sex being female, and a higher recipient MELD score all correspond to a higher log-odds of delayed liver graft function. Donor intraoperative hemodynamic instability, on the other hand, correlated with a decreased log-odds, suggesting that patients who are hemodynamically stable have lower delayed liver graft function.

We felt our methodology was largely appropriate, as it allows us to determine the probabilities of binary outcomes, such as the one we are observing through donor hyperglycemia. Additionally, since the log odds ensure probabilities fall between 0 and 1, this method allows us to have a more standardized way of analyzing data and holding variables constant while we observe others. However, this isn't to say there wasn't room for improvement. Some drawbacks of the log-odds model we used were that it assumes linearity and that it isn't able to adjust for the effect of multiple variables at once. Additionally, the inclusion of this model is not as compatible with a lay audience as the comparisons are less intuitive. There are also potential flaws within our data, as we are not completely sure if the data was collected accurately and there may be selection bias as donors with incomplete glucose data were not included in the data set analysis.

If we were to repeat this study or obtain our own data, we would take several steps to have a more robust scientific conclusion. Firstly, we wouldn't assume linearity and might try to fit nonlinear models to our data to try to find the best possible fit and prediction. Additionally, we would perform sensitivity analyses to ensure that small changes in variables or data collection wouldn't alter the data significantly. Lastly, if feasible, we would want to include more variables within our exploration so that we can predict potential confounding factors and see a wider range of potential changes to liver function. Some of these new variables may include the donor's history of diabetes and cause of death, to better understand their health levels, as well as more information about the liver graft, such as preservation techniques and weight ratios to limit confounding variables. Altogether, these changes could allow for us to better our understanding of this issue in the future and promote research towards manipulating donor factors to prioritize healthy liver graft function.
